spring:
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${MINIO_HOST:localhost}:${MYSQL_PORT:3306}/yout
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:adminadmin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: #email
    password: #password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
  data:
    redis:
      host: localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/oauth2/jwks

server:
  forward-headers-strategy: native


#server:
#  ssl:
#    key-store: classpath:certs/domain.p12
#    key-store-password: 5122

application:
  path:
    default-user-picture: classpath:/picture/default-picture.png
  url:
    user-picture-upload: http://localhost:8080/api/image/user
    default-user-picture: http://localhost:8080/api/image/user/default
    recommendations-service: http://localhost:8010/recs


object-storage:
  root-folder: video-api
  url: http://${OBJECT_STORAGE_HOST:localhost}:9000
  access-key: ${OBJECT_STORAGE_ACCESS:admin}
  secret-key: ${OBJECT_STORAGE_SECRET:adminadmin}

logging:
  logback:
    rollingpolicy:
      max-file-size:
        5MB






